impl the Error trait for the ErrorKind | custom error handler is useful to specify the exact type of error at runtime instead of using Box<dyn Error> which handles all possible errors at runtime dynamically and may causes the app gets panicked at runtime